name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: devops-backend
  ECR_REGISTRY: 294069345642.dkr.ecr.ap-south-1.amazonaws.com

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.sha }} .

      # 5. Tag image for ECR
      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY:${{ github.sha }} \
          $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

      # 6. Push image to ECR
      - name: Push to ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

      # 7. Update Kubernetes manifest with new image
      - name: Update deployment YAML
        run: |
          sed -i "s|image: .*|image: $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}|g" backend/backend-deployment.yaml

      # 8. Commit and push changes (GitOps trigger)
      - name: Push updated manifest
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add backend/backend-deployment.yaml
          git commit -m "Update image" || echo "No changes"
          git push
